# データベースインポート用の一時的な設定
# 使用後は必ず停止してください
services:
  phpmyadmin:
    deploy:
      replicas: 1
    ports:
      - "8091:80"
    # セキュリティのため、特定のIPからのみアクセス可能にする場合
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOSTS: ${PMA_HOSTS}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
